### ISSUE TITLE
Android: Vertical Flatlist nested in horizontal InfinitePager not scrolling

### ISSUE THREAD

**Issue by Insanefoam** [computerjazz/react-native-infinite-pager#18]
Hello!
I want to make vertical Flatlist nested in horizontal InfinitePager, something like Google Calendar day view. But Flatlist doesn't scroll. Tried to pass `nestedScrollEnabled` prop into Flatlist, but it got no effect.

My code looks like this:
 ```
  <InfinitePager
        renderPage={(props) => {
          <View style={[scheduleDaysContainerStyles.root]}>
            <FlatList
              data={weekDays}
              keyExtractor={(item) => item.toISOString()}
              showsVerticalScrollIndicator={false}
              renderItem={({ item }) => (
                <View style={[scheduleDayContainerStyles.root]}>
                  <ScheduleDay
                    week={selectedWeek}
                    day={item}
                    scheduledRecipes={
                      recipes?.filter((recipe) =>
                        dayjs(recipe.date).isSame(item, 'day'),
                      ) ?? []
                    }
                    onSchedule={onSchedule}
                  />
                </View>
              )}
              ListFooterComponent={<View style={[listFooterStyles.root]} />}
              nestedScrollEnabled
            />
          </View>;
        }}
        pageBuffer={1}
        onPageChange={(page) =>
          setSelectedWeek(getNextWeek(selectedWeek, page))
        }
        ref={pagerRef}
      />   
```

I tested this on Android Emulator and real device -- both have problem. But, on IOS Emulator this code works fine. I started to explore the source code of the library, because it's the only one bug that I have. If you can help me i'll be very appreciated!

**Comment by ryskin-taskie** [comment]
But what If I need to use Animated.FlatList?

**Comment by computerjazz** [comment]
can you wrap it in `createAnimatedComponent`? https://docs.swmansion.com/react-native-reanimated/docs/core/createAnimatedComponent/#:~:text=createAnimatedComponent%20lets%20you%20create%20an,Animated.
