### ISSUE TITLE
Same content shows for other pages too while partial swipe

### ISSUE THREAD

**Issue by inthisar-hamza** [computerjazz/react-native-infinite-pager#25]
In My project, the same content shows for other pages too till swipe to the next page completely, and the data depends on onPageChange but while partial swipe and hold the content was the same for both pages. 

additionally, I need to attach other gesture handlers to detect swiping left or right to add the animation for the inside content while swiping, How can I do this? 

I haven't learned animation yet. if there are ways to handle it give code samples, for now.

**Comment by computerjazz** [comment]
i'd have to see some code to help. why does the data depend on `onPageChange`?

**Comment by inthisar-hamza** [comment]
> i'd have to see some code to help. why does the data depend on `onPageChange`?

It's a day switcher that is integrated with infinite pager and onPageChange triggers the data change, in current implementation, and looking for a good fix or another approach.

I will give code sample tomorrow.

**Comment by inthisar-hamza** [comment]
> i'd have to see some code to help. why does the data depend on `onPageChange`?

Is there any way to add swipe event for detect swipe left or right then I can change data quickly than wait for onPageChange event occured.

Give me some code sample for it, I noticed there are gesture something in your docs.

**Comment by inthisar-hamza** [comment]
> i'd have to see some code to help. why does the data depend on `onPageChange`?

That works fine with another approach accessing specific data by object's string key and day swapping done by index. Good work 💯 helpful library, 

does multiple flatlist as infinite page component make performance issues? Is there are any downside?
