### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by ErionTp** [computerjazz/react-native-infinite-pager#30]
Hello, first of all thank you for this amazing library. 

Im trying to implement this in a project which is supposed to be opened even in web but i get:

`Cannot access 'pageInterpolatorCube' before initialization`

Kindly can you check it?

**Comment by ErionTp** [comment]
After investigating, the library works the same even in web. The problem seems to be in the `pageInterpolators.ts`. The line: `export const defaultPageInterpolator = pageInterpolatorSlide;` should be after the `pageInterpolatorSlide` function.

If you ca edit please

**Comment by krvns** [comment]
As of right now this is not fixed in v0.3.17
