### ISSUE TITLE
Can't detect swipe direction

### ISSUE THREAD

**Issue by ryanliljestrom** [computerjazz/react-native-infinite-pager#6]
I want to use this package to make something similar to [react-native-calendar-strip](https://www.npmjs.com/package/react-native-calendar-strip) for a project. One of our requirements is that a date is always selected as the user swipes through the weeks.

The functionality I want:

* If the user swipes to the previous week, it automatically selects the Friday of that week (closest business day)
* If the user swipes to the next week, it automatically selects the Monday of that week

I can't currently find a way to detect if the swipe is a left swipe or a right swipe. I think if `onPageChange` were modified to provide the previous page as an (optional) second argument, it would give me the information I need

**Comment by computerjazz** [comment]
hm, not a bad idea to include prev data in `onPageChange`.

You can get the info you want via an animated reaction, see this snack: https://snack.expo.dev/@computerjazz/infinite-pager-detect-direction
