### ISSUE TITLE
how to use Pager as Lazy component.

### ISSUE THREAD

**Issue by crzycoder** [computerjazz/react-native-infinite-pager#7]
I want to use this infinity pager as a lazy component like wen view comes into visiable then the screen render

**Comment by computerjazz** [comment]
you can use either `isActive` boolean or listen to the `focusAnim` reanimated value to gate screen rendering: https://github.com/computerjazz/react-native-infinite-pager/blob/aa5a2d08743798a89a691eb2cd04fbabd781b8c8/src/index.tsx#L307-L308
